project('llvm', 'c', 'cpp', version: '22.1.7', license: 'Apache-2.0 WITH LLVM-exception')

if host_machine.system() != 'windows'
    error('Cannot use Windows LLVM binaries on other OS!')
endif

cxx = meson.get_compiler('cpp')
llvm_dep = declare_dependency(include_directories: get_option('buildtype') / 'include', dependencies: [
    cxx.find_library('LLVMAnalysis', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMAsmParser', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMBinaryFormat', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMBitReader', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMBitstreamReader', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMCore', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMDebugInfoCodeView', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMDebugInfoDWARF', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMDebugInfoDWARFLowLevel', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMDebugInfoPDB', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMDemangle', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMDWARFCFIChecker', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMFrontendAtomic', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMFrontendDirective', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMFrontendDriver', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMFrontendHLSL', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMFrontendOffloading', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMFrontendOpenMP', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMIRReader', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMMC', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMMCParser', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMObject', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMObjectYAML', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMOption', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMPlugins', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMProfileData', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMRemarks', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMScalarOpts', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMSupport', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMTargetParser', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMTextAPI', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMTransformUtils', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('LLVMWindowsDriver', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangAnalysis', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangAnalysisLifetimeSafety', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangAPINotes', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangAST', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangASTMatchers', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangBasic', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangDriver', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangEdit', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangExtractAPI', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangFrontend', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangIndex', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangLex', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangOptions', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangParse', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangRewrite', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangSema', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangSerialization', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangSupport', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('clangTooling', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib'),
    cxx.find_library('libclang', required: true, dirs: meson.current_source_dir() / get_option('buildtype') / 'lib')
])
